remote_theme: rosario/kasper
name: How I Code Stuff
title: How I Code Stuff
description: My journey in Machine Learning and Web Application Development
meta_description: "Web Application Development, Machine Learning, IoT, Linux and fun!"
google_analytics: UA-112579131-1

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
comments: true
siteurl: https://howicodestuff.github.io
baseurl: '/'
domain_name: 'https://howicodestuff.github.io'
gems:
  - jekyll-paginate
  - jekyll-github-metadata

# Details for the RSS feed generator
url: 'https://howicodestuff.github.io/blog'
author: 'Christos Zonios'
