remote_theme: rosario/kasper

name: How I Code Stuff
description: Walk through coding with me
meta_description: "How I Code Stuff Blog by Christos Zonios"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://howicodestuff.github.io'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://howicodestuff.github.io/blog'
author:         'Christos Zonios'
