remote_theme: rosario/kasper
name: How I Code Stuff
title: How I Code Stuff
description: Walk through coding with me
meta_description: "Web Application Development, Machine Learning, IoT, Linux and fun!"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
comments: true
baseurl: '/'
domain_name: 'https://howicodestuff.github.io'
plugins: [jekyll-paginate, jekyll-github-metadata]

# Details for the RSS feed generator
url: 'https://howicodestuff.github.io/blog'
author: 'Christos Zonios'
